server:
  port: 8070
  servlet:
    context-path: /

logging.level:
  org.apache.kafka: ERROR

info:
  name: '@project.name@'
  version: '@project.version@'
  description: '@project.description@'

spring:
  data:
    mongodb:
      database: mongo-kafka

kafka:
  bootstrap-servers: localhost:9092
  topic:
    request: request-model
    response: response-model
  group: api